update workflow

diff --git a/.github/workflows/deploy_terraform_project.yaml b/.github/workflows/deploy_terraform_project.yaml
--- a/.github/workflows/deploy_terraform_project.yaml
+++ b/.github/workflows/deploy_terraform_project.yaml
@@ -12,7 +12,8 @@ jobs:
     name: Deploy Terraform Project
     runs-on: arc-runners
     outputs:
-      projects: ${{ steps.collect-artifacts.outputs.projects }}
+      project: ${{ steps.collect-artifacts.outputs.project }}
+      ansible_limit: ${{ steps.collect-artifacts.outputs.ansible_limit }}
     env:
       VAULT_ADDR: ${{ vars.VAULT_ADDR }}
       VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
@@ -23,6 +24,26 @@ jobs:
         with:
           repository: eingram-homelab/terraform
           ref: main
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v46.0.5
+        with:
+          files: |
+            projects/**/**/*.tf
+
+      - name: Ensure only one project is changed
+        id: check-projects
+        run: |
+          if [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
+            projects=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '([a-zA-Z]+\/)+')
+            unique_project=$(echo "$projects" | sort -u)
+            if [ $(echo "$unique_project" | wc -l) -gt 1 ]; then
+              echo "Error: More than one project changed. Please limit changes to one project at a time."
+              exit 1
+            fi
+            echo "project=$unique_project" >> $GITHUB_OUTPUT
+          fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -38,19 +59,10 @@ jobs:
         run: |
           echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json
 
-      - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v46.0.5
-        with:
-          files: |
-            projects/**/**/*.tf
-
       - name: Generate backend configuration
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            dir=$(dirname "$file")
-            cat > "$dir/backend.tf" <<EOF
+          dir=${{ steps.check-projects.outputs.project }}
+          cat > "$dir/backend.tf" <<EOF
           terraform {
             backend "gcs" {
               bucket      = "yc-srv1-tfstate"
@@ -59,48 +71,35 @@ jobs:
             }
           }
           EOF
-            echo "Generated backend.tf for $dir"
-          done
+          echo "Generated backend.tf for $dir"
 
       - name: Check terraform fmt
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            dir=$(dirname "$file")
-            echo "Running terraform fmt for $dir"
-            cd "$dir"
-            terraform fmt -check
-          done
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform fmt for $dir"
+          cd "$dir"
+          terraform fmt -check
 
       - name: Run terraform init
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            dir=$(dirname "$file")
-            echo "Running terraform init for $dir"
-            cd "$dir"
-            terraform init
-          done
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform init for $dir"
+          cd "$dir"
+          terraform init
 
       - name: Run terraform validate
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            dir=$(dirname "$file")
-            echo "Running terraform validate for $dir"
-            cd "$dir"
-            terraform validate
-          done
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform validate for $dir"
+          cd "$dir"
+          terraform validate
 
       - name: Run terraform apply
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            dir=$(dirname "$file")
-            echo "Running terraform apply for $dir"
-            cd "$dir"
-            terraform apply --auto-approve
-          done
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform apply for $dir"
+          cd "$dir"
+          terraform apply --auto-approve
 
       - name: Install jq
         run: |
@@ -109,27 +108,31 @@ jobs:
 
       - name: Collect artifacts
         id: collect-artifacts
-        if: steps.changed-files.outputs.all_changed_files != ''
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            echo "Collecting artifacts from $dir"
-            dir=$(dirname "$file")
-            name=$(basename $dir)
-            type=$(echo "$dir" | cut -d'/' -f3)
-            cd "$dir"
-            ip_address=$(terraform output -json default_ip_address | jq -r '.[0]')
-            # Create json from artifacts
-            JSON_STRING+=$( jq -n \
-                  --arg nm "$name" \
-                  --arg ty "$type" \
-                  --arg ip "$ip_address" \
-                  '{name: $nm, type: $ty, ip_address: $ip}' )
-            echo "$JSON_STRING" >> "$GITHUB_OUTPUT"
-          done
-
-  # test:
-  #   name: Run post build tests
-  #   runs-on: arc-runners
+          echo "Collecting artifacts from $dir"
+          dir=${{ steps.check-projects.outputs.project }}
+          echo project_name=$(basename $dir) >> $GITHUB_OUTPUT
+          type=$(echo "$dir" | cut -d'/' -f3)
+          cd "$dir"
+          if [ $type == "vsphere" ]; then
+            domain=$(terraform output -json dns_suffix | jq -r '.[0]')
+            names=$(terraform output -json name | jq -r '.')
+            while IFS= read -r item; do
+              name_list+=("$item")
+            done < <(jq -c '.[]' <<< "$names")
+            for i in "${!name_list[@]}"; do
+              name_list[$i]="${name_list[$i]}"."$domain"
+            done
+            echo ansible_limit="$(IFS=,; echo "${name_list[*]}")" >> $GITHUB_OUTPUT
+            echo $GITHUB_OUTPUT
+            
+  # call_post_deploy_vsphere_workflow:
   #   needs: deploy
-  #   steps:
-  #     - name: 
+  #   if: needs.deploy.outputs.project == 'vsphere'
+  #   uses: eingram-homelab/ansible-col-homelab/.github/workflows/test_reusable.yaml@main
+  #   with:
+  #     ansible_limit: ${{ needs.deploy.outputs.ansible_limit }}
+    
+
+
+    
