update workflow

diff --git a/.github/workflows/deploy_terraform_project.yaml b/.github/workflows/deploy_terraform_project.yaml
--- a/.github/workflows/deploy_terraform_project.yaml
+++ b/.github/workflows/deploy_terraform_project.yaml
@@ -159,14 +159,6 @@ jobs:
             fi
           fi
 
-      - name: Run terraform destroy if unable to retrieve artifacts
-        if: steps.collect-artifacts.outcome == 'failure'
-        run: |
-          dir=${{ steps.check-projects.outputs.project }}
-          echo "Running terraform destroy for $dir"
-          cd "$dir"
-          terraform destroy --auto-approve
-
   call_post_deploy_vsphere_workflow:
     needs: deploy
     if: needs.deploy.outputs.project == 'vsphere'
@@ -175,3 +167,82 @@ jobs:
       limit: ${{ needs.deploy.outputs.ansible_limit }}
       playbook: "new_build.yaml"
       extra_vars: "hostvar=all"
+
+  run_terraform_destroy:
+    runs-on: arc-runners
+    if: always()
+    env:
+      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
+      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
+      GCP_STORAGE: ${{ secrets.GCP_STORAGE }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          repository: eingram-homelab/terraform
+          ref: main
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v46.0.5
+        with:
+          files: |
+            projects/**/**/*.tf
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@main
+        with:
+          terraform_version: 1.11.3
+
+      - name: Create json cred file
+        run: |
+          echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json
+
+      - name: Ensure only one project is changed
+        id: check-projects
+        run: |
+          if [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
+            echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
+            projects=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '.+\/')
+            echo ${projects[@]}
+            unique_project=$(echo "$projects" | sort -u)
+            echo $unique_project
+            if [ $(echo "$unique_project" | wc -l) -gt 1 ]; then
+              echo "Error: More than one project changed. Please limit changes to one project at a time."
+              exit 1
+            fi
+            echo "project=$unique_project" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Generate backend configuration
+        run: |
+          dir=${{ steps.check-projects.outputs.project }}
+          cat > "$dir/backend.tf" <<EOF
+          terraform {
+            backend "gcs" {
+              bucket      = "yc-srv1-tfstate"
+              credentials = "/tmp/cred.json"
+              prefix      = "terraform/state/$(echo "$dir" | cut -d'/' -f3)-$(basename "$dir")"
+            }
+          }
+          EOF
+          echo "Generated backend.tf for $dir"
+
+      - name: Run terraform init
+        run: |
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform init for $dir"
+          cd "$dir"
+          terraform init
+
+      - name: Run terraform destroy
+        run: |
+          dir=${{ steps.check-projects.outputs.project }}
+          echo "Running terraform destroy for $dir"
+          cd "$dir"
+          terraform destroy --auto-approve
