comment

diff --git a/.github/workflows/deploy_terraform_project.yaml b/.github/workflows/deploy_terraform_project.yaml
--- a/.github/workflows/deploy_terraform_project.yaml
+++ b/.github/workflows/deploy_terraform_project.yaml
@@ -177,84 +177,84 @@ jobs:
       ansible_user: ${{ needs.deploy.outputs.ansible_user }}
     secrets: inherit
 
-  run_terraform_destroy:
-    needs:
-      - deploy
-      - call_post_deploy_vsphere_workflow
-    runs-on: arc-runners
-    if: ${{ always() && ((needs.deploy.steps.collect-artifacts.outcome == 'failure') || (needs.call_post_deploy_vsphere_workflow.result == 'failure')) }}
-    env:
-      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
-      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
-      GCP_STORAGE: ${{ secrets.GCP_STORAGE }}
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          repository: eingram-homelab/terraform
-          ref: develop
+  # run_terraform_destroy:
+  #   needs:
+  #     - deploy
+  #     - call_post_deploy_vsphere_workflow
+  #   runs-on: arc-runners
+  #   if: ${{ always() && ((needs.deploy.steps.collect-artifacts.outcome == 'failure') || (needs.call_post_deploy_vsphere_workflow.result == 'failure')) }}
+  #   env:
+  #     VAULT_ADDR: ${{ vars.VAULT_ADDR }}
+  #     VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
+  #     GCP_STORAGE: ${{ secrets.GCP_STORAGE }}
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: eingram-homelab/terraform
+  #         ref: develop
 
-      - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v46.0.5
-        with:
-          files: |
-            projects/**/**/*.tf
+  #     - name: Get changed files
+  #       id: changed-files
+  #       uses: tj-actions/changed-files@v46.0.5
+  #       with:
+  #         files: |
+  #           projects/**/**/*.tf
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20'
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@main
-        with:
-          terraform_version: 1.11.3
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@main
+  #       with:
+  #         terraform_version: 1.11.3
 
-      - name: Create json cred file
-        run: |
-          echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json
+  #     - name: Create json cred file
+  #       run: |
+  #         echo ${{ secrets.GCP_STORAGE }} | base64 --decode > /tmp/cred.json
 
-      - name: Ensure only one project is changed
-        id: check-projects
-        run: |
-          if [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
-            echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
-            projects=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '.+\/')
-            echo ${projects[@]}
-            unique_project=$(echo "$projects" | sort -u)
-            echo $unique_project
-            if [ $(echo "$unique_project" | wc -l) -gt 1 ]; then
-              echo "Error: More than one project changed. Please limit changes to one project at a time."
-              exit 1
-            fi
-            echo "project=$unique_project" >> $GITHUB_OUTPUT
-          fi
+  #     - name: Ensure only one project is changed
+  #       id: check-projects
+  #       run: |
+  #         if [ "${{ steps.changed-files.outputs.all_changed_files }}" != "" ]; then
+  #           echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
+  #           projects=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE '.+\/')
+  #           echo ${projects[@]}
+  #           unique_project=$(echo "$projects" | sort -u)
+  #           echo $unique_project
+  #           if [ $(echo "$unique_project" | wc -l) -gt 1 ]; then
+  #             echo "Error: More than one project changed. Please limit changes to one project at a time."
+  #             exit 1
+  #           fi
+  #           echo "project=$unique_project" >> $GITHUB_OUTPUT
+  #         fi
 
-      - name: Generate backend configuration
-        run: |
-          dir=${{ steps.check-projects.outputs.project }}
-          cat > "$dir/backend.tf" <<EOF
-          terraform {
-            backend "gcs" {
-              bucket      = "yc-srv1-tfstate"
-              credentials = "/tmp/cred.json"
-              prefix      = "terraform/state/$(echo "$dir" | cut -d'/' -f3)-$(basename "$dir")"
-            }
-          }
-          EOF
-          echo "Generated backend.tf for $dir"
+  #     - name: Generate backend configuration
+  #       run: |
+  #         dir=${{ steps.check-projects.outputs.project }}
+  #         cat > "$dir/backend.tf" <<EOF
+  #         terraform {
+  #           backend "gcs" {
+  #             bucket      = "yc-srv1-tfstate"
+  #             credentials = "/tmp/cred.json"
+  #             prefix      = "terraform/state/$(echo "$dir" | cut -d'/' -f3)-$(basename "$dir")"
+  #           }
+  #         }
+  #         EOF
+  #         echo "Generated backend.tf for $dir"
 
-      - name: Run terraform init
-        run: |
-          dir=${{ steps.check-projects.outputs.project }}
-          echo "Running terraform init for $dir"
-          cd "$dir"
-          terraform init
+  #     - name: Run terraform init
+  #       run: |
+  #         dir=${{ steps.check-projects.outputs.project }}
+  #         echo "Running terraform init for $dir"
+  #         cd "$dir"
+  #         terraform init
 
-      - name: Run terraform destroy
-        run: |
-          dir=${{ steps.check-projects.outputs.project }}
-          echo "Running terraform destroy for $dir"
-          cd "$dir"
-          terraform destroy --auto-approve
+  #     - name: Run terraform destroy
+  #       run: |
+  #         dir=${{ steps.check-projects.outputs.project }}
+  #         echo "Running terraform destroy for $dir"
+  #         cd "$dir"
+  #         terraform destroy --auto-approve
